### ISSUE TITLE
Documentation for Redis/Celery setup

### ISSUE THREAD

**Issue by rpetit3** [Phelimb/BIGSI#39]
I've put together a large (~400gb) BIGSI database and would like to make use of your docker-compose setup. Unfortunately, after trying `docker-compose up` I'm not sure on what to do next.

Would it be possible to get documentation for using your docker-compose files? Or, a brief example of how to utilize Redis/Celery with BIGSI?

Thank you very much!

**Comment by Phelimb** [comment]
Hi @rpetit3, 

Unfortunately, the redis backend is currently not working on tip of master. 

I'll try to reactivate the code for that backend and add some documentation. For now, I would recommend using the `rocksdb` branch and backend and use the command line version rather than the docker-compose version.

**Comment by rpetit3** [comment]
Thanks for the update @Phelimb !

In the future, is BIGSI going to be switching to RocksDB instead of BerkeleyDB? If so, is there a method to convert an existing BIGSI databases over to RocksDB? Or, is rebuilding it the simplest solution.

**Comment by Phelimb** [comment]
I hope to be able to support both databases. RocksDB has some advantages for a BIGSI of similar samples as it supports native compression. However, I've had colleagues reporting technical issues on shared filesystems and install problems. 

I'm currently working on merging the branches. Hope to have an update by next week. It is possible to convert between the DBs so I'll make sure to upload a script which supports this.

**Comment by Phelimb** [comment]
Redis is now available in the v0.3.1 release
