### ISSUE TITLE
visualisation software used for figures in the publication (Ultrafast search of all deposited bacterial and viral genomic data)

### ISSUE THREAD

**Issue by AhmedArslan** [Phelimb/BIGSI#47]
Hi, I want to know the software/package you used to get figures of papers especially very clean fig.4?

**Comment by Phelimb** [comment]
Hi Ahmed, 

Figure 4 was generated with phandango (https://jameshadfield.github.io/phandango/#/). The other data figures were generated with the R package ggplot (https://ggplot2.tidyverse.org/reference/ggplot.html). 

Hope that helps!
