### ISSUE TITLE
(Pdf request) Paper upload onto GitHub 

### ISSUE THREAD

**Issue by jolespin** [Phelimb/BIGSI#53]
I tried emailing the corresponding author but can’t access the actual email without nature biotechnology access.  Is it possible to upload the pdf onto your github?  It seems like a really interesting paper and a method that I would like to incorporate in my pipelines.

**Comment by iqbal-lab** [comment]
I don't think we're allowed to put the paper on github. The preprint explains the method well, but the benchmarking is less good
https://www.biorxiv.org/content/early/2017/12/15/234955
I'm the corresponding author but don't recall your email? Did you mail zi@ebi.ac.uk? I can email you it

**Comment by jolespin** [comment]
Yea, that was me.  Thank you!
