### ISSUE TITLE
about k-mer extraction

### ISSUE THREAD

**Issue by jiadong324** [Phelimb/BIGSI#58]
Dear all,

What exactly in the .ctx file after using McCortex? I am using Jellyfish, I need to understand that file for the next step.

Thanks!

**Comment by iqbal-lab** [comment]
Its a binary file format representing the de bruijn graph
https://github.com/iqbal-lab/cortex/blob/master/doc/binary_file_format.txt
mccortex allows you to query it, and to get the kmers out

**Comment by jiadong324** [comment]
@iqbal-lab Thanks for your reply. Btw, does BIGSI only use the .ctx file for building the BloomFilter? If I write my own code, do I need to convert the k-mers to CTX format?

Thanks!

**Comment by iqbal-lab** [comment]
No no, BIGSI takes a list of kmers, you can go directly from jellyfish. We used. Ctx because we like the error cleaning methods cortex and mccortex use. We should clarify the documentation

**Comment by jiadong324** [comment]
Well, when I look through the example at https://bigsi.readme.io/docs/your-first-bigsi. In step 3, it takes .CTX file as input to create the .bloom file. It is unclear for me how to do it without a .CTX file. Since Jellyfish generally outputs K-mer and its count, it would be great if you can provide an example without using .CTX file.

Thanks!

**Comment by apetkau** [comment]
I hope it's appropriate for me to comment on this issue. I'm facing the same trouble. I can get BIGSI to run with a **ctx** file, but it's not clear to me how to use the output of Jellyfish for BIGSI. Would I be using the same command `bigsi bloom [jellyfish file] [output]`?

**Comment by iqbal-lab** [comment]
It can take a simple list of kmers. See the example here
https://bigsi.readme.io/docs/your-first-bigsi
Your repo contains the example file
https://github.com/Phelimb/BIGSI/blob/master/example-data/kmers.txt

**Comment by iqbal-lab** [comment]
Hope that clarifies. We use mccortex simply to remove putative errors, you can use a kmer list that you obtain any way you like

**Comment by apetkau** [comment]
Woops. I must have missed that in the docs. Thanks so much 👍

**Comment by iqbal-lab** [comment]
No worries
