### ISSUE TITLE
Cannot create .ctx file

### ISSUE THREAD

**Issue by Tj-Idowu** [Phelimb/BIGSI#60]
Hi,

I'm following the "Constructing a BIGSI" instructions and I'm having trouble with the first step "Extract k-mers from your data". I followed the sample code exactly with both my data and the sample fasta file you provided and the ctx files created doesn't contain enough characters for it to be relevant:

`CORTEX^F^@^@^@?^@^@^@^B^@^@^@^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^E^@^@^@test1^@أp=
ף<F8>?^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@      ^@^@^@undefinedCORTEX`

This is all that is contained within the ctx file. Any help you can offer would be much appreciated. Thank you.

**Comment by iqbal-lab** [comment]
the ctx file is a binary file. it's an encoding of a de bruijn graph - how big was your input data?

**Comment by Tj-Idowu** [comment]
There are multiple files but they range between 360 and 800 MB.
